# Image GPS Matching

This notebook matches each image/annotation with its corresponding GPS data based on the Cityscapes `image_id`.

For each image and annotation (e.g. `"aachen_000000_000019_leftImg8bit.png"` and `"aachen_000000_000019_gtFine_color.png"`), 
there exists a corresponding JSON file `"aachen_000000_000019_vehicle.json"` containing GPS metadata.

The `match_images_with_gps()` function takes as arguments:
- The path to the root directory of the Cityscapes dataset
- The annotation type (`"gtFine"` or `"gtCoarse"`) to set the correct directories for annotations and JSON files

And returns a DataFrame with columns `["split", "city", "image_id", "latitude", "longitude"]` for each image/annotation.

In [ ]:
import json
from tqdm import tqdm
import pandas as pd
from pathlib import Path

def match_images_with_gps(data_path, annotation_type):
    """
    Matches Cityscapes images with their corresponding GPS coordinates. 
    
    Pairing each image with GPS metadata from its corresponding vehicle JSON file based on matching image IDs.
    """

     # Set directory paths based on annotation type
    if annotation_type == "gtFine":
        annot_path = data_path / "gtFine_trainvaltest" / annotation_type
        json_path = data_path / "vehicle_trainvaltest/vehicle"

        # Fine annotations have train, val, and test splits
        split_paths = list(annot_path.glob("*"))
        splits = [split_path.name for split_path in split_paths]

    elif annotation_type == "gtCoarse":
        annot_path = data_path /"gtCoarse" / annotation_type
        json_path = data_path / "vehicle_trainextra/vehicle"

        # Coarse annotations only have train_extra split
        splits = ["train_extra"]
    else:
        print('Invalid annotation type provided. Valid types are "gtFine" or "gtCoarse".')
        return None

    result_rows = []

    # Iterate through all splits
    for split in splits:
        # Iterate through all cities in the split
        city_paths = list((annot_path / split).glob("*"))
        for city_path in city_paths:
            city = city_path.name
            
            # Get all annotation files for this city
            img_paths = list(city_path.glob(f"*_{annotation_type}_color.png"))
        
            for img_path in tqdm(img_paths, total=len(img_paths), desc=f"{annotation_type}: Matching images in {city}"):
                # Extract image_id by removing the annotation type suffix
                image_id = img_path.name.replace(f"_{annotation_type}_color.png", "")

                # Read corresponding GPS data from vehicle JSON file
                json_file = json_path / split / city / f"{image_id}_vehicle.json"
                
                if not json_file.exists():
                    print(f"JSON-File at {json_file} does not exist")
                    continue
                
                with open(json_file, "r") as file:
                    data = json.load(file)
                
                 # Add result row with image_id and GPS data
                result_rows.append({
                    "split": split,
                    "city": city,
                    "image_id": image_id,
                    "latitude": data["gpsLatitude"],
                    "longitude": data["gpsLongitude"]
                })

    return pd.DataFrame(result_rows)

## Process Both Cityscapes Variants

Apply GPS matching to both fine and coarse Cityscapes datasets (`"gtFine"` and `"gtCoarse"`).

In [21]:
data_path = Path("../data/City Scapes")

cityscapes_fine_gps_data = match_images_with_gps(data_path, "gtFine")
cityscapes_fine_gps_data.head()

gtFine: Matching images in berlin: 100%|██████████| 544/544 [00:00<00:00, 5468.01it/s]
gtFine: Matching images in bielefeld: 100%|██████████| 181/181 [00:00<00:00, 7523.97it/s]
gtFine: Matching images in bonn: 100%|██████████| 46/46 [00:00<00:00, 5749.56it/s]
gtFine: Matching images in leverkusen: 100%|██████████| 58/58 [00:00<00:00, 6152.18it/s]
gtFine: Matching images in mainz: 100%|██████████| 298/298 [00:00<00:00, 4900.66it/s]
gtFine: Matching images in munich: 100%|██████████| 398/398 [00:00<00:00, 5637.71it/s]
gtFine: Matching images in aachen: 100%|██████████| 174/174 [00:00<00:00, 6082.20it/s]
gtFine: Matching images in bochum: 100%|██████████| 96/96 [00:00<00:00, 4661.20it/s]
gtFine: Matching images in bremen: 100%|██████████| 316/316 [00:00<00:00, 6447.97it/s]
gtFine: Matching images in cologne: 100%|██████████| 154/154 [00:00<00:00, 8205.95it/s]
gtFine: Matching images in darmstadt: 100%|██████████| 85/85 [00:00<00:00, 6258.95it/s]
gtFine: Matching images in dusseldorf: 100%|██████████| 221/221 [00:00<00:00, 6240.85it/s]
gtFine: Matching images in erfurt: 100%|██████████| 109/109 [00:00<00:00, 4263.30it/s]
gtFine: Matching images in hamburg: 100%|██████████| 248/248 [00:00<00:00, 6365.90it/s]
gtFine: Matching images in hanover: 100%|██████████| 196/196 [00:00<00:00, 7242.39it/s]
gtFine: Matching images in jena: 100%|██████████| 119/119 [00:00<00:00, 4101.39it/s]
gtFine: Matching images in krefeld: 100%|██████████| 99/99 [00:00<00:00, 5322.04it/s]
gtFine: Matching images in monchengladbach: 100%|██████████| 94/94 [00:00<00:00, 5250.91it/s]
gtFine: Matching images in strasbourg: 100%|██████████| 365/365 [00:00<00:00, 6617.54it/s]
gtFine: Matching images in stuttgart: 100%|██████████| 196/196 [00:00<00:00, 5952.47it/s]
gtFine: Matching images in tubingen: 100%|██████████| 144/144 [00:00<00:00, 6047.90it/s]
gtFine: Matching images in ulm: 100%|██████████| 95/95 [00:00<00:00, 5588.64it/s]
gtFine: Matching images in weimar: 100%|██████████| 142/142 [00:00<00:00, 6878.77it/s]
gtFine: Matching images in zurich: 100%|██████████| 122/122 [00:00<00:00, 5581.30it/s]
gtFine: Matching images in frankfurt: 100%|██████████| 267/267 [00:00<00:00, 6214.37it/s]
gtFine: Matching images in lindau: 100%|██████████| 59/59 [00:00<00:00, 9798.22it/s]
gtFine: Matching images in munster: 100%|██████████| 174/174 [00:00<00:00, 7310.74it/s]

  split    city              image_id   latitude  longitude
0  test  berlin  berlin_000000_000019  52.497751  13.295325
1  test  berlin  berlin_000001_000019  52.498672  13.300393
2  test  berlin  berlin_000002_000019  52.499890  13.306958
3  test  berlin  berlin_000003_000019  52.499929  13.307324
4  test  berlin  berlin_000004_000019  52.498154  13.306086

In [22]:
cityscapes_coarse_gps_data = match_images_with_gps(data_path, "gtCoarse")
cityscapes_coarse_gps_data.head()

gtCoarse: Matching images in augsburg: 100%|██████████| 1504/1504 [00:10<00:00, 146.63it/s]
gtCoarse: Matching images in bad-honnef: 100%|██████████| 97/97 [00:00<00:00, 148.45it/s]
gtCoarse: Matching images in bamberg: 100%|██████████| 445/445 [00:02<00:00, 148.81it/s]
gtCoarse: Matching images in bayreuth: 100%|██████████| 855/855 [00:05<00:00, 146.95it/s]
gtCoarse: Matching images in dortmund: 100%|██████████| 1112/1112 [00:07<00:00, 147.33it/s]
gtCoarse: Matching images in dresden: 100%|██████████| 422/422 [00:02<00:00, 148.42it/s]
gtCoarse: Matching images in duisburg: 100%|██████████| 825/825 [00:05<00:00, 151.83it/s]
gtCoarse: Matching images in erlangen: 100%|██████████| 265/265 [00:01<00:00, 151.81it/s]
gtCoarse: Matching images in freiburg: 100%|██████████| 847/847 [00:05<00:00, 152.24it/s]
gtCoarse: Matching images in heidelberg: 100%|██████████| 1201/1201 [00:08<00:00, 146.64it/s]
gtCoarse: Matching images in heilbronn: 100%|██████████| 730/730 [00:04<00:00, 150.23it/s]
gtCoarse: Matching images in karlsruhe: 100%|██████████| 1152/1152 [00:07<00:00, 146.07it/s]
gtCoarse: Matching images in konigswinter: 100%|██████████| 118/118 [00:00<00:00, 148.14it/s]
gtCoarse: Matching images in konstanz: 100%|██████████| 1527/1527 [00:10<00:00, 148.01it/s]
gtCoarse: Matching images in mannheim: 100%|██████████| 1181/1181 [00:07<00:00, 148.86it/s]
gtCoarse: Matching images in muhlheim-ruhr: 100%|██████████| 1224/1224 [00:08<00:00, 146.64it/s]
gtCoarse: Matching images in nuremberg: 100%|██████████| 1485/1485 [00:10<00:00, 147.27it/s]
gtCoarse: Matching images in oberhausen: 100%|██████████| 903/903 [00:06<00:00, 148.66it/s]
gtCoarse: Matching images in saarbrucken: 100%|██████████| 554/554 [00:03<00:00, 150.85it/s]
gtCoarse: Matching images in schweinfurt: 100%|██████████| 710/710 [00:04<00:00, 151.15it/s]
gtCoarse: Matching images in troisdorf:  71%|███████   | 98/138 [00:00<00:00, 151.28it/s]

JSON-File at ..\data\City Scapes\vehicle_trainextra\vehicle\train_extra\troisdorf\troisdorf_000000_000073_vehicle.json does not exist

gtCoarse: Matching images in troisdorf: 100%|██████████| 138/138 [00:00<00:00, 149.26it/s]
gtCoarse: Matching images in wuppertal: 100%|██████████| 1081/1081 [00:07<00:00, 151.93it/s]
gtCoarse: Matching images in wurzburg: 100%|██████████| 1622/1622 [00:11<00:00, 145.36it/s]

         split      city                image_id   latitude  longitude
0  train_extra  augsburg  augsburg_000000_000000  48.371323  10.886690
1  train_extra  augsburg  augsburg_000000_000001  48.371254  10.887023
2  train_extra  augsburg  augsburg_000000_000002  48.371205  10.887244
3  train_extra  augsburg  augsburg_000000_000003  48.371137  10.887553
4  train_extra  augsburg  augsburg_000000_000004  48.371093  10.887759

## Export GPS-Matched DataFrames

Export the `image_id` and corresponding GPS coordinates as CSV files

In [23]:
cityscapes_fine_gps_data.to_csv("../output/cityscapes_fine_gps_data.csv")
cityscapes_coarse_gps_data.to_csv("../output/cityscapes_coarse_gps_data.csv")